#!/bin/sh /etc/rc.common
# author: xiaofan <xfan1024@live.com>

START=80
USE_PROCD=1
bin="/usr/bin/udp2raw"

start_udp2raw() {
	local cfg="$1"
	local first_opt="$2"
	local localaddr remoteaddr mode key cipher auth disabled

	config_get_bool disabled $cfg disabled
	[ "$disabled" = 1 ] && return
	config_get localaddr $cfg localaddr
	config_get remoteaddr $cfg remoteaddr
	config_get mode $cfg mode
	config_get key $cfg key
	config_get cipher $cfg cipher
	config_get auth $cfg auth
	config_get_bool iptables $cfg iptables

	procd_open_instance
	procd_set_param command "$bin"
	procd_append_param command "$first_opt"
	[ -n "$localaddr" ] && procd_append_param command -l "$localaddr"
	[ -n "$remoteaddr" ] && procd_append_param command -r "$remoteaddr"
	[ -n "$mode" ] && procd_append_param command --raw-mode "$mode"
	[ -n "$key" ] && procd_append_param command -k "$key"
	[ -n "$cipher" ] && procd_append_param command --cipher-mode "$cipher"
	[ -n "$auth" ] && procd_append_param command --auth-mode "$auth"
	[ -n "$iptables" ] && procd_append_param command -a --keep-rule
	procd_close_instance
}

start_service() {
	config_load udp2raw
	config_foreach start_udp2raw client "-c"
	config_foreach start_udp2raw server "-s"
}
