#!/bin/sh /etc/rc.common
# author: xiaofan <xfan1024@live.com>

START=80
USE_PROCD=1
bin="/usr/bin/udp2raw"
confdir="/var/etc/udp2raw"

confpath=""
conf_make(){
	mkdir -p "$confdir"
	confpath="$confdir/$1.conf"
	echo "# this conf generate by udp2raw.$1" >"$confpath"
}
conf_append(){
	echo "$*" >>"$confpath"
}

start_udp2raw() {
	local cfg="$1"
	local first_opt="$2"
	local confdir confpath
	local localaddr remoteaddr mode key cipher auth disabled

	config_get_bool disabled $cfg disabled
	[ "$disabled" = 1 ] && return

	conf_make "$cfg"

	config_get localaddr $cfg localaddr
	config_get remoteaddr $cfg remoteaddr
	config_get mode $cfg mode
	config_get key $cfg key
	config_get cipher $cfg cipher
	config_get auth $cfg auth
	config_get_bool iptables $cfg iptables

	procd_open_instance
	procd_set_param command "$bin" --conf-file "$confpath"
	conf_append "$first_opt"
	[ -n "$localaddr" ] && conf_append -l "$localaddr"
	[ -n "$remoteaddr" ] && conf_append -r "$remoteaddr"
	[ -n "$mode" ] && conf_append --raw-mode "$mode"
	[ -n "$key" ] && conf_append -k "$key"
	[ -n "$cipher" ] && conf_append --cipher-mode "$cipher"
	[ -n "$auth" ] && conf_append --auth-mode "$auth"
	[ -n "$iptables" ] && conf_append -a --keep-rule
	procd_close_instance
}

start_service() {
	config_load udp2raw
	config_foreach start_udp2raw client "-c"
	config_foreach start_udp2raw server "-s"
}
